In [1]:
%load_ext autoreload
%autoreload 2

# Paper action masking
https://arxiv.org/abs/2006.14171

In [2]:
import numpy as np
from stable_baselines3 import PPO
import torch as th
from players import TorchPlayer, RandomPlayer, GreedyPlayer, evaluate_player, DictPolicyPlayer
from helper import SelfPlayEnv

In [74]:
N = 1000

# Board shape 4

In [7]:
board_shape = 4
random_player_2 = RandomPlayer(board_shape=board_shape)
greedy_player_2 = GreedyPlayer(board_shape=board_shape)
dict_policy_player_2 = DictPolicyPlayer(board_shape=board_shape)


In [10]:
model = PPO.load('models/PPO_4by4_0.99_0.95_0.0_10_8_masked/best_model.zip')
board_shape = model.observation_space.shape[1]
player = TorchPlayer(model, board_shape=board_shape, deterministic=True)
_ = evaluate_player(player, random_player_2, N=N)

Using cache found in /home/jupyter-julian/.cache/torch/hub/pytorch_vision_v0.9.0


Wins as first: 0.806
Wins as second: 0.976
Ties as first: 0.056
Ties as second: 0.0
Plays as first: 500
Plays as first: 500


# Board shape 8

In [75]:
board_shape = 8
random_player_2 = RandomPlayer(board_shape=board_shape)
greedy_player_2 = GreedyPlayer(board_shape=board_shape)

In [76]:
model_1 = PPO.load('models/PPO_8by8_0.99_0.95_0.0_10_8_masked/best_model-01.zip')
board_shape = model.observation_space.shape[1]
torch_player_1 = TorchPlayer(model_1, board_shape=board_shape, deterministic=True)

Using cache found in /home/jupyter-julian/.cache/torch/hub/pytorch_vision_v0.9.0


In [77]:
_ = evaluate_player(torch_player_1, random_player_2, N=N)

Wins as first: 0.8434237995822874
Wins as second: 0.8867562380036685
Ties as first: 0.018789144050100463
Ties as second: 0.01919385796544737
Plays as first: 479
Plays as second: 521
Avg game duration as first: 14.450999999998555
Avg game duration as second: 15.568999999998443


In [78]:
model_2 = PPO.load('models/PPO_8by8_0.99_0.95_0.0_10_8_masked/best_model.zip')
board_shape = model.observation_space.shape[1]
torch_player_2 = TorchPlayer(model_2, board_shape=board_shape, deterministic=True)

Using cache found in /home/jupyter-julian/.cache/torch/hub/pytorch_vision_v0.9.0


In [79]:
_ = evaluate_player(torch_player_2, random_player_2, N=N)

Wins as first: 0.8444444444442739
Wins as second: 0.8772277227721036
Ties as first: 0.022222222222217734
Ties as second: 0.021782178217817468
Plays as first: 495
Plays as second: 505
Avg game duration as first: 14.973999999998503
Avg game duration as second: 15.09399999999849


In [73]:
torch_player_1 = TorchPlayer(model_1, board_shape=board_shape, deterministic=False)
torch_player_2 = TorchPlayer(model_2, board_shape=board_shape, deterministic=True, flatten_action=False)
_ = evaluate_player(torch_player_1, torch_player_2, N=100, eps=0)

Wins as first: 0.36585365853658536
Wins as second: 0.3559322033898305
Ties as first: 0.0
Ties as second: 0.01694915254237288
Plays as first: 41
Plays as second: 59
Avg game duration as first: 12.38
Avg game duration as second: 17.51


In [72]:
torch_player_1 = TorchPlayer(model_1, board_shape=board_shape, deterministic=True)
torch_player_2 = TorchPlayer(model_2, board_shape=board_shape, deterministic=False, flatten_action=False)
_ = evaluate_player(torch_player_1, torch_player_2, N=100)

Wins as first: 0.605263157893144
Wins as second: 0.5967741935474246
Ties as first: 0.02631578947361496
Ties as second: 0.032258064516077004
Plays as first: 38
Plays as second: 62
Avg game duration as first: 11.47999999998852
Avg game duration as second: 18.47999999998152


In [21]:
board_shape = 8
model_1 = PPO.load('models/PPO_8by8_0.99_0.95_0.0_10_8_masked/best_model-01.zip')
torch_player_1 = TorchPlayer(model_1, board_shape=board_shape, deterministic=True)

model_2 = PPO.load('models/PPO_8by8_0.99_0.95_0.0_10_8_masked/best_model.zip')
torch_player_2 = TorchPlayer(model_2, board_shape=board_shape, deterministic=True, flatten_action=False)

_ = evaluate_player(torch_player_1, torch_player_2, N=100, verbose=0)

Using cache found in /home/jupyter-julian/.cache/torch/hub/pytorch_vision_v0.9.0
Using cache found in /home/jupyter-julian/.cache/torch/hub/pytorch_vision_v0.9.0


Wins as first: 0.0
Wins as second: 0.9999999999981818
Ties as first: 0.0
Ties as second: 0.0
Plays as first: 45
Plays as second: 55


In [56]:
board_shape = 8
model_1 = PPO.load('models/PPO_8by8_0.99_0.95_0.0_10_8_masked/best_model-01.zip')
torch_player_1 = TorchPlayer(model_1, board_shape=board_shape, deterministic=False, flatten_action=False)

model_2 = PPO.load('models/PPO_8by8_0.99_0.95_0.0_10_8_masked/best_model.zip')
torch_player_2 = TorchPlayer(model_2, board_shape=board_shape, deterministic=False)

_ = evaluate_player(torch_player_2, torch_player_1, N=10)

Using cache found in /home/jupyter-julian/.cache/torch/hub/pytorch_vision_v0.9.0
Using cache found in /home/jupyter-julian/.cache/torch/hub/pytorch_vision_v0.9.0


Wins as first: 0.599999999988
Wins as second: 0.399999999992
Ties as first: 0.0
Ties as second: 0.0
Plays as first: 5
Plays as second: 5


In [5]:
model_1 = PPO.load('models/PPO_8by8_0.99_0.95_0.0_10_8_masked/best_model-01.zip')
torch_player_1 = TorchPlayer(model_1, board_shape=board_shape, deterministic=True, flatten_action=False)

model_2 = PPO.load('models/PPO_8by8_0.99_0.95_0.0_10_8_masked/best_model.zip')
torch_player_2 = TorchPlayer(model_2, board_shape=board_shape, deterministic=True, flatten_action=False)

Using cache found in /home/jupyter-julian/.cache/torch/hub/pytorch_vision_v0.9.0
Using cache found in /home/jupyter-julian/.cache/torch/hub/pytorch_vision_v0.9.0


In [6]:
from boardgame2 import ReversiEnv

In [7]:
env = ReversiEnv()

In [52]:
done = False
(obs, player) = env.reset()
while not done:
    print(player, end='/')
    if player == 1:
        action = torch_player_2.predict(obs * player)
    else:
        action = torch_player_1.predict(obs * player)
    (obs, player), reward, done, _ = env.step(action)
reward

1/-1/1/-1/1/-1/1/-1/1/-1/1/-1/1/-1/1/-1/1/-1/1/-1/1/-1/1/-1/1/-1/1/-1/1/-1/1/-1/1/-1/1/-1/1/-1/1/-1/1/-1/1/-1/1/-1/1/-1/1/-1/1/-1/1/-1/1/-1/1/-1/-1/-1/

-1

In [9]:
model = PPO.load('models/PPO_8by8_0.99_0.95_0.0_10_8_masked/best_model.zip')
board_shape = model.observation_space.shape[1]
player = TorchPlayer(model, board_shape=board_shape, deterministic=True)
_ = evaluate_player(player, RandomPlayer, N=1000)

Using cache found in /home/jupyter-julian/.cache/torch/hub/pytorch_vision_v0.9.0


Wins as first: 0.8830409356725146
Wins as second: 0.8891170431211499
Ties as first: 0.025341130604288498
Ties as second: 0.02053388090349076
Plays as first: 513
Plays as first: 487


In [11]:
def get_valid_actions(board):
    self_play_env.get_valid((board, 1)).reshape(-1) 
    return self_play_env.get_valid((board, 1)).reshape(-1) 
model.policy.set_get_valid_actions(get_valid_actions)

In [12]:
board_shape = model.observation_space.shape[1]

# player = GreedyPlayer(env, 1, flatten_action=True)
player = TorchPlayer(model, board_shape=board_shape, deterministic=True)
# player = TorchPlayer(env, model, deterministic=False)

In [13]:
wins_as_first = 0
plays_as_first = 0
wins_as_second = 0
plays_as_second = 0
N = 10
for i in range(N):
    self_play_env = SelfPlayEnv(board_shape=board_shape, Player=RandomPlayer, verbose=0)
    done = False
    board = self_play_env.reset()
    while not done:
        action = player.predict(board)
        board, reward, done, _ = self_play_env.step(action)
    if self_play_env.local_player_num == -1:
        wins_as_first = wins_as_first + (reward == 1)
        plays_as_first = plays_as_first + 1
    else:
        wins_as_second = wins_as_second + (reward == 1)
        plays_as_second = plays_as_second + 1

In [14]:
wins_as_first/plays_as_first, wins_as_second/plays_as_second

(0.7142857142857143, 1.0)

In [57]:
plays_as_first, plays_as_second

(505, 495)

deterministic actions
contra random: (0.9230769230769231, 0.8688524590163934)
model contra greedy: (1.0, 1.0)

sample actions
model contra random: (0.8125, 0.8461538461538461)
model contra greedy: (0.8163265306122449, 0.7254901960784313)

In [512]:
self_play_env = SelfPlayEnv(board_shape=board_shape, Player=GreedyPlayer, verbose=1)
done = False
board = self_play_env.reset()
while not done:
    action = player.predict(board)
    board, reward, done, _ = self_play_env.step(action)
print(reward)

You play with -1
Initial board
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  1 -1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
[2 4] False
Plays oponent:
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  1  0  0  0]
 [ 0  0  0  1  1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
Step: 1
You play:
[2, 3]
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
Plays oponent:
[2 2] False
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  1  1  1  0  0  0]
 [ 0  0  0  1  1  0  0  0]
 [ 0  0  0 -1  1  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
Reward: -0.0
Step: 2
Y

In [172]:
221/500, 207/500

(0.442, 0.414)

In [154]:
# self_play_env.get_winner(board)

In [54]:
board

array([[ 0,  0, -1,  0],
       [ 0, -1, -1,  0],
       [ 0,  1, -1,  0],
       [ 0,  0,  0,  0]], dtype=int8)

In [17]:
# env = ReversiEnv(board_shape=4)
# self_play_env.Player(env, 1)

In [19]:
env = ReversiEnv(board_shape=4)
obs = env.reset()[0]

In [20]:
obs

array([[ 0,  0,  0,  0],
       [ 0,  1, -1,  0],
       [ 0, -1,  1,  0],
       [ 0,  0,  0,  0]], dtype=int8)

In [21]:
gp = GreedyPlayer(env, 1)

In [181]:
gp.predict(obs)

array([0, 2])